FROM node:16

CMD [ "npm", "run", "dev" ]

RUN mkdir -p /home/node/app && chown -R node:node /home/node/app
WORKDIR /home/node/app

USER node

COPY --chown=node:node package.json package-lock.json ./
RUN npm ci

# Bundle app source
COPY --chown=node:node . ./
