name: Smoke Test
on:
  schedule:
    - cron: 0 */6 * * *
jobs:
  end-to-end-smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install python dependencies
        working-directory: ./end-to-end-tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check running containers
        run: docker ps -a
      - name: Run robot tests
        working-directory: ./end-to-end-tests
        run: robot --variable SERVER:${{secrets.PRODUCTION_URL}} --variable BROWSER:headlessfirefox -t "Staging server is up and front page on test url is reachable" tests/staging.robot